---
name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
permissions:
  contents: read
  packages: write
jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: go test
        run: |
          go test -v ./...